---
- name: "generate the server locale"
  locale_gen: name={{ locale }} state=present

- name: "set locale"
  lineinfile: dest=/etc/default/locale regexp='^LANG' line='LANG={{ locale }}'

- name: "reload locale"
  raw: . /etc/default/locale

- name: "set /etc/localtime"
  command: /bin/cp /usr/share/zoneinfo/{{ timezone }} /etc/localtime

- name: "Install additional software"
  apt:
    pkg: "{{ item }}"
    state: installed
    update_cache: yes
  with_items:
  - dnsutils
  - git
  - vim
  - ntp
  - at
  - lvm2
  - build-essential
  - python2.7
  - python-pip
  - python-dev
  - build-essential

- name: create python symlink
  file:
    src: /usr/bin/python2.7
    dest: /usr/bin/python
    owner: root
    group: root
    state: link

- name: Update Pip
  command: pip install --upgrade pip
  become: true
