--- 
- name: Setup server
  hosts: localhost
  become: true # become sudo
  gather_facts: False
  pre_tasks:
    - name: "apt-get update"
      raw: apt-get update -qq
    - name: "apt-get upgrade"
      raw: apt-get upgrade -qq
    - raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
    - setup: # aka gather_facts
  roles:
    - general
    - users
    - bof_git
    - lamp
